{{- if .Values.dockerconfigjson -}}
apiVersion: v1
kind: Secret
metadata:
  name: skitleregistrysecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
{{- end -}}
