openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://skitle.com/status
paths:
  /status:
    get:
      tags:
        - Status
      parameters:
        - in: path
          required: true
          name: taskID
          schema:
            type: integer

      responses:
        200:
          description: ""
        401:
          description: ""
        500:
          description: ""
