openapi: 3.0.5
info:
  title: "Skitle - Fixme"
  version: 1.0.0
paths:
  "/login":
    post:
      responses:
        200:
          description: "Succesful login"
        401:
          description: "Incorrect credentials"

  "/register":
    post:
      responses:
        201:
          description: "Succesful registration"
        400:
          description: "Incorrect register payload"
