apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jobs
  name: jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
      - image: {{ .Values.werf.image.jobs }}
        name: jobs
        ports:
        - containerPort: 8080
          name: jobs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobs
  name: jobs
spec:
  ports:
  - name: "jobs-service"
    port: 80
  selector:
    app: jobs
